kind: workflow
description: some workflow 2

entity-type: env_resource
label-selector: vm

inputs:
    volume_id:
        type: String
        default: 'volume-1'
jobs:
    job1:
        kind: shell
        spec:
            agent:
                name: yakir-dev-eks
            sources:
                - store: yakir-opa
                  path: scripts/print-resource.sh
            commands:
                - name: print
                  command:  './print-resource.sh {{ .bindings.resource_id }} {{ .inputs.volume_id }} {{ .params.token }}'
            outputs:
                - print
