kind: workflow
description: some workflow 2

entity-type: env_resource
label-selector: vm

inputs:
  volume_id:
    type: String
    default: 'volume-1'

outputs:
  job_output: '{{ .jobs.job1.outputs.print }}'
  
jobs:
    job1:
        kind: shell
        spec:
            agent:
                name: yakir-dev-eks
            sources:
                - store: test-spec2-public
                  path: scripts/print-resource.sh
            commands:
                - name: print
                  command:  './print-resource.sh {{ .bindings.resource_id }} {{ .inputs.volume_id }} {{ .params.token }}'
            outputs:
                - print

    job2:
        kind: shell
        depends-on: job1
        spec:
            agent:
                name: yakir-dev-eks            
            commands:
                - name: print
                  command:  'echo hello'
            outputs:
                - print
