kind: workflow
description: some workflow 2

entity-type: env_resource
label-selector: vm

inputs:
  volume_id:
    type: string
    default: 'volume-1'

outputs:
  job1_output: '{{ .jobs.job1.outputs.print }}'
  job2_output: '{{ .jobs.job2.outputs.print }}'
  workflow_input: '{{ .inputs.volume_id }}'
  
jobs:
    job1:
        kind: shell
        spec:
            agent:
                name: yakir-dev-eks
            sources:
                - store: test-spec2-public
                  path: scripts/print-resource.sh
            commands:
                - name: print
                  command:  'source print-resource.sh {{ .bindings.resource_id }} {{ .bindings.grain_path }} {{ .params.token }}'
            outputs:
                - print

    job2:
        kind: shell
        depends-on: job1
        spec:
            agent:
                name: yakir-dev-eks            
            commands:
                - command: 'echo hello from job2' 
                - name: print
                  command:  'export print="job2 - {{ .jobs.job1.outputs.print}}"'
            outputs:
                - print
